name: Java CI

on: [push]

jobs:
  build_dependency_challenge:

    name: Build Dependency Challenge
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Grant execute permission for gradlew
      working-directory: Backend/dependency
      run: chmod +x gradlew
    - name: Build with Gradle
      working-directory: Backend/dependency
      run: ./gradlew build

  build_mapping_challenge:

    name: Build mapping Challenge
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Grant execute permission for gradlew
      working-directory: Backend/mapping
      run: chmod +x gradlew
    - name: Build with Gradle
      working-directory: Backend/mapping
      run: ./gradlew build